### ISSUE TITLE
about naming and version

### ISSUE THREAD

**Issue by nineclue** [elixir-cldr/cldr_calendars_chinese#3]
Hi,

Congratulations and thanks for release of 1.0. 

When I use :cldr_calendars_lunisolar I get following error message, `Failed to fetch record for cldr_calendars_lunisolar from registry (using cache instead)`

If I change the name to :ex_cldr_calendars_lunisolar I get `Because your app depends on ex_cldr_calendars_lunisolar ~> 1.0 which doesn't match any versions, version solving failed` 

I've searched for **cldr_calendars_lunisolar** at hex.pm, result contains only ex_cldr_calendars_lunisolar 1.0.0-beta.1 which was released Jan 31, 2022. 

I can't figure out how to use the 1.0 version. Any help would be appreciated.

**Comment by kipcole9** [comment]
I did mess up the names of some of the calendar libs. They are all expected to be `ex_cldr_calendars_*`. Belatedly I re-published with the correct name `ex_cldr_calendrs_lunisolar`:
```elixir
% mix hex.info ex_cldr_calendars_lunisolar
Implementation of Lunisolar Chinese, Japanese and Korean calendars for Elixir

Config: {:ex_cldr_calendars_lunisolar, "~> 1.0"}
Releases: 1.0.0, 1.0.0-beta.1

Licenses: Apache-2.0
Links:
  Changelog: https://github.com/elixir-cldr/cldr_calendars_lunisolar/blob/v1.0.0/CHANGELOG.md
  GitHub: https://github.com/elixir-cldr/cldr_calendars_lunisolar
  Readme: https://github.com/elixir-cldr/cldr_calendars_lunisolar/blob/v1.0.0/README.md
```
So I think the issue was timing (ie a screwup on my side). If you try again I think you should be ok.

**Comment by nineclue** [comment]
Thanks again, now works without any problems!
